import type { Color } from "@prisma/client";

export const bgColor20: Record<Color, string> = {
  BERRY_RED: "bg-berry-red/20",
  RED: "bg-red/20",
  ORANGE: "bg-orange/20",
  YELLOW: "bg-yellow/20",
  OLIVE_GREEN: "bg-olive-green/20",
  LIME_GREEN: "bg-lime-green/20",
  GREEN: "bg-green/20",
  MINT_GREEN: "bg-mint-green/20",
  TEAL: "bg-teal/20",
  SKY_BLUE: "bg-sky-blue/20",
  LIGHT_BLUE: "bg-light-blue/20",
  BLUE: "bg-blue/20",
  GRAPE: "bg-grape/20",
  VIOLET: "bg-violet/20",
  LAVENDER: "bg-lavender/20",
  MAGENTA: "bg-magenta/20",
  SALMON: "bg-salmon/20",
  CHARCOAL: "bg-charcoal/20",
  GREY: "bg-grey/20",
  TAUPE: "bg-taupe/20",
};

export const bgHoverColor50: Record<Color, string> = {
  BERRY_RED: "custom-hover:bg-berry-red/50",
  RED: "custom-hover:bg-red/50",
  ORANGE: "custom-hover:bg-orange/50",
  YELLOW: "custom-hover:bg-yellow/50",
  OLIVE_GREEN: "custom-hover:bg-olive-green/50",
  LIME_GREEN: "custom-hover:bg-lime-green/50",
  GREEN: "custom-hover:bg-green/50",
  MINT_GREEN: "custom-hover:bg-mint-green/50",
  TEAL: "custom-hover:bg-teal/50",
  SKY_BLUE: "custom-hover:bg-sky-blue/50",
  LIGHT_BLUE: "custom-hover:bg-light-blue/50",
  BLUE: "custom-hover:bg-blue/50",
  GRAPE: "custom-hover:bg-grape/50",
  VIOLET: "custom-hover:bg-violet/50",
  LAVENDER: "custom-hover:bg-lavender/50",
  MAGENTA: "custom-hover:bg-magenta/50",
  SALMON: "custom-hover:bg-salmon/50",
  CHARCOAL: "custom-hover:bg-charcoal/50",
  GREY: "custom-hover:bg-grey/50",
  TAUPE: "custom-hover:bg-taupe/50",
};

export const bgHoverColor80: Record<Color, string> = {
  BERRY_RED: "custom-hover:bg-berry-red/80",
  RED: "custom-hover:bg-red/80",
  ORANGE: "custom-hover:bg-orange/80",
  YELLOW: "custom-hover:bg-yellow/80",
  OLIVE_GREEN: "custom-hover:bg-olive-green/80",
  LIME_GREEN: "custom-hover:bg-lime-green/80",
  GREEN: "custom-hover:bg-green/80",
  MINT_GREEN: "custom-hover:bg-mint-green/80",
  TEAL: "custom-hover:bg-teal/80",
  SKY_BLUE: "custom-hover:bg-sky-blue/80",
  LIGHT_BLUE: "custom-hover:bg-light-blue/80",
  BLUE: "custom-hover:bg-blue/80",
  GRAPE: "custom-hover:bg-grape/80",
  VIOLET: "custom-hover:bg-violet/80",
  LAVENDER: "custom-hover:bg-lavender/80",
  MAGENTA: "custom-hover:bg-magenta/80",
  SALMON: "custom-hover:bg-salmon/80",
  CHARCOAL: "custom-hover:bg-charcoal/80",
  GREY: "custom-hover:bg-grey/80",
  TAUPE: "custom-hover:bg-taupe/80",
};

export const textColor: Record<Color, string> = {
  BERRY_RED: "text-berry-red",
  RED: "text-red",
  ORANGE: "text-orange",
  YELLOW: "text-yellow",
  OLIVE_GREEN: "text-olive-green",
  LIME_GREEN: "text-lime-green",
  GREEN: "text-green",
  MINT_GREEN: "text-mint-green",
  TEAL: "text-teal",
  SKY_BLUE: "text-sky-blue",
  LIGHT_BLUE: "text-light-blue",
  BLUE: "text-blue",
  GRAPE: "text-grape",
  VIOLET: "text-violet",
  LAVENDER: "text-lavender",
  MAGENTA: "text-magenta",
  SALMON: "text-salmon",
  CHARCOAL: "text-charcoal",
  GREY: "text-grey",
  TAUPE: "text-taupe",
};
