const bgColor20 = {
  "Berry Red": "bg-berry-red/20",
  Red: "bg-red/20",
  Orange: "bg-orange/20",
  Yellow: "bg-yellow/20",
  "Olive Green": "bg-olive-green/20",
  "Lime Green": "bg-lime-green/20",
  Green: "bg-green/20",
  "Mint Green": "bg-mint-green/20",
  Teal: "bg-teal/20",
  "Sky Blue": "bg-sky-blue/20",
  "Light Blue": "bg-light-blue/20",
  Blue: "bg-blue/20",
  Grape: "bg-grape/20",
  Violet: "bg-violet/20",
  Lavender: "bg-lavender/20",
  Magenta: "bg-magenta/20",
  Salmon: "bg-salmon/20",
  Charcoal: "bg-charcoal/20",
  Grey: "bg-grey/20",
  Taupe: "bg-taupe/20",
};

const hoverBgColor50 = {
  "Berry Red": "hover:bg-berry-red/50",
  Red: "hover:bg-red/50",
  Orange: "hover:bg-orange/50",
  Yellow: "hover:bg-yellow/50",
  "Olive Green": "hover:bg-olive-green/50",
  "Lime Green": "hover:bg-lime-green/50",
  Green: "hover:bg-green/50",
  "Mint Green": "hover:bg-mint-green/50",
  Teal: "hover:bg-teal/50",
  "Sky Blue": "hover:bg-sky-blue/50",
  "Light Blue": "hover:bg-light-blue/50",
  Blue: "hover:bg-blue/50",
  Grape: "hover:bg-grape/50",
  Violet: "hover:bg-violet/50",
  Lavender: "hover:bg-lavender/50",
  Magenta: "hover:bg-magenta/50",
  Salmon: "hover:bg-salmon/50",
  Charcoal: "hover:bg-charcoal/50",
  Grey: "hover:bg-grey/50",
  Taupe: "hover:bg-taupe/50",
};

const hoverBgColor80 = {
  "Berry Red": "hover:bg-berry-red/80",
  Red: "hover:bg-red/80",
  Orange: "hover:bg-orange/80",
  Yellow: "hover:bg-yellow/80",
  "Olive Green": "hover:bg-olive-green/80",
  "Lime Green": "hover:bg-lime-green/80",
  Green: "hover:bg-green/80",
  "Mint Green": "hover:bg-mint-green/80",
  Teal: "hover:bg-teal/80",
  "Sky Blue": "hover:bg-sky-blue/80",
  "Light Blue": "hover:bg-light-blue/80",
  Blue: "hover:bg-blue/80",
  Grape: "hover:bg-grape/80",
  Violet: "hover:bg-violet/80",
  Lavender: "hover:bg-lavender/80",
  Magenta: "hover:bg-magenta/80",
  Salmon: "hover:bg-salmon/80",
  Charcoal: "hover:bg-charcoal/80",
  Grey: "hover:bg-grey/80",
  Taupe: "hover:bg-taupe/80",
};

const textColor = {
  "Berry Red": "text-berry-red",
  Red: "text-red",
  Orange: "text-orange",
  Yellow: "text-yellow",
  "Olive Green": "text-olive-green",
  "Lime Green": "text-lime-green",
  Green: "text-green",
  "Mint Green": "text-mint-green",
  Teal: "text-teal",
  "Sky Blue": "text-sky-blue",
  "Light Blue": "text-light-blue",
  Blue: "text-blue",
  Grape: "text-grape",
  Violet: "text-violet",
  Lavender: "text-lavender",
  Magenta: "text-magenta",
  Salmon: "text-salmon",
  Charcoal: "text-charcoal",
  Grey: "text-grey",
  Taupe: "text-taupe",
};

export { bgColor20, hoverBgColor50, hoverBgColor80, textColor };
